Traceback (most recent call last):
  File "/home-nfs/lorell/miniconda3/envs/baby/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home-nfs/lorell/miniconda3/envs/baby/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home-nfs/lorell/SparseDebugging/src/__main__.py", line 33, in <module>
    main()
  File "/home-nfs/lorell/SparseDebugging/src/__main__.py", line 30, in main
    run(depth=args.depth, augmentation=args.aug, mparams=args.mparams, position=args.position, fsmult=args.fsmult, kdiv=args.kdiv, auxweight=args.auxweight, loadmodel=args.load, usecase=args.usecase, prefix=args.prefix)
  File "/home-nfs/lorell/SparseDebugging/src/app.py", line 84, in run
    train_epochs(EPOCHS, auxweight, model, trainloader, testloader, criterion, optimizer, LRDROPS, LRFACTOR, TAG, usecase, loadmodel=loadmodel)
  File "/home-nfs/lorell/SparseDebugging/src/app.py", line 160, in train_epochs
    avg_train_loss, grads, mags = train_epoch(model, auxweight, trainloader, criterion, optimizer, usecase)
  File "/home-nfs/lorell/SparseDebugging/src/app.py", line 285, in train_epoch
    raise Exception('Unknown usecase "{}"'.format(usecase))
Exception: Unknown usecase ""
